# Generated by Django 5.2 on 2025-05-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
                ('unit_price', models.PositiveIntegerField()),
                ('discount_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
